"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, LoaderCircle, LockKeyhole, Mail } from "lucide-react";
import { useRouter } from "next/navigation";

export function AuthForm({ mode }: { mode: "login" | "register" | "request-reset" }) {
  const router = useRouter();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [consent, setConsent] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState<{ text: string; verificationUrl?: string } | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const endpoint = mode === "login" ? "/api/auth/login" : mode === "register" ? "/api/auth/register" : "/api/auth/request-reset"; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(mode === "request-reset" ? { email } : mode === "register" ? { email, password, consent } : { email, password }) }); const data = await response.json() as { ok?: boolean; error?: string; verificationUrl?: string; emailSent?: boolean }; if (!response.ok) throw new Error(data.error || "Une erreur est survenue."); if (mode === "login") { router.push("/tableau-de-bord"); return; } setSuccess({ text: mode === "register" ? data.emailSent ? "Compte créé. Consultez votre boîte mail pour vérifier votre adresse." : "Compte créé. Le service d’envoi d’email doit être configuré pour recevoir le lien de vérification." : "Si un compte correspond à cette adresse, un lien de réinitialisation a été envoyé.", verificationUrl: data.verificationUrl }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Une erreur est survenue."); } finally { setLoading(false); } }
  if (success) return <div className="rounded-[1.5rem] border border-border bg-white p-7 text-center shadow-[0_18px_60px_rgba(10,35,46,.08)]"><CheckCircle2 className="mx-auto h-12 w-12 text-primary" /><h2 className="mt-4 text-2xl font-black text-ink">C’est enregistré</h2><p className="mt-2 leading-7 text-muted-foreground">{success.text}</p>{success.verificationUrl && <a className="button-primary mt-5" href={success.verificationUrl}>Lien local de vérification</a>}<div><Link className="mt-5 inline-block font-bold text-primary underline" href="/connexion" prefetch={false}>Aller à la connexion</Link></div></div>;
  const title = mode === "login" ? "Bon retour" : mode === "register" ? "Créer votre espace" : "Réinitialiser le mot de passe";
  return <div className="rounded-[1.5rem] border border-border bg-white p-6 shadow-[0_18px_60px_rgba(10,35,46,.08)] sm:p-8"><h1 className="text-3xl font-black tracking-tight text-ink">{title}</h1><p className="mt-2 leading-6 text-muted-foreground">{mode === "login" ? "Retrouvez vos démarches sauvegardées." : mode === "register" ? "Un email valide suffit. Nous ne demandons aucun identifiant administratif." : "Saisissez votre adresse. La réponse ne révèle jamais si un compte existe."}</p><form className="mt-7 grid gap-5" onSubmit={submit}>
    <label><span className="form-label">Adresse email</span><div className="relative"><Mail className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" /><input className="form-input pl-12" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></div></label>
    {mode !== "request-reset" && <label><span className="form-label">Mot de passe</span><div className="relative"><LockKeyhole className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" /><input className="form-input pl-12" type="password" autoComplete={mode === "register" ? "new-password" : "current-password"} minLength={mode === "register" ? 12 : 1} required value={password} onChange={(event) => setPassword(event.target.value)} /></div>{mode === "register" && <p className="mt-2 text-xs text-muted-foreground">12 caractères minimum, avec majuscule, minuscule et chiffre.</p>}</label>}
    {mode === "register" && <label className="flex items-start gap-3 text-sm leading-6 text-muted-foreground"><input className="mt-1 h-4 w-4 accent-primary" type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} required /><span>J’accepte les <Link className="font-bold underline" href="/conditions" prefetch={false}>conditions d’utilisation</Link> et j’ai lu la <Link className="font-bold underline" href="/confidentialite" prefetch={false}>politique de confidentialité</Link>.</span></label>}
    {error && <p className="rounded-xl border border-destructive/20 bg-red-50 p-3 text-sm font-semibold text-destructive" role="alert">{error}</p>}
    <button className="button-primary justify-center" disabled={loading}>{loading ? <LoaderCircle className="h-5 w-5 animate-spin" /> : <>{mode === "login" ? "Se connecter" : mode === "register" ? "Créer mon compte" : "Envoyer le lien"}<ArrowRight className="h-5 w-5" /></>}</button>
  </form>{mode === "login" && <div className="mt-5 flex flex-wrap justify-between gap-3 text-sm"><Link className="font-bold text-primary underline" href="/mot-de-passe-oublie" prefetch={false}>Mot de passe oublié ?</Link><Link className="font-bold text-primary underline" href="/inscription" prefetch={false}>Créer un compte</Link></div>}{mode === "register" && <p className="mt-5 text-center text-sm text-muted-foreground">Déjà inscrit ? <Link className="font-bold text-primary underline" href="/connexion" prefetch={false}>Se connecter</Link></p>}</div>;
}
