"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CalendarDays, Download, FileText, LoaderCircle, LogOut, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { useRouter } from "next/navigation";

type User = { id: string; email: string; role: string; emailVerifiedAt: string | null };
type Procedure = { id: string; type: string; title: string; updatedAt: string };
type Payment = { id: string; kind: string; status: string; amountCents: number; currency: string; subscriptionId?: string; createdAt: string };

export function Dashboard() {
  const router = useRouter();
  const [user, setUser] = useState<User | null | undefined>(undefined); const [procedures, setProcedures] = useState<Procedure[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [cancelling, setCancelling] = useState<string | null>(null);
  useEffect(() => { Promise.all([fetch("/api/auth/me").then(async (r) => await r.json() as { user: User | null }), fetch("/api/procedures").then(async (r) => r.ok ? await r.json() as { procedures: Procedure[] } : { procedures: [] }), fetch("/api/payments").then(async (r) => r.ok ? await r.json() as { payments: Payment[] } : { payments: [] })]).then(([me, saved, history]) => { setUser(me.user); setProcedures(saved.procedures || []); setPayments(history.payments || []); }).catch(() => setUser(null)); }, []);
  if (user === undefined) return <div className="flex min-h-[50vh] items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-primary" /></div>;
  if (!user) return <div className="rounded-[1.75rem] border border-border bg-white p-8 text-center"><ShieldCheck className="mx-auto h-12 w-12 text-primary" /><h1 className="mt-4 text-3xl font-black text-ink">Connectez-vous pour retrouver vos démarches</h1><p className="mx-auto mt-3 max-w-xl leading-7 text-muted-foreground">Vous pouvez utiliser les parcours sans compte. Un espace est nécessaire uniquement pour sauvegarder et exporter.</p><div className="mt-6 flex justify-center gap-3"><Link className="button-primary" href="/connexion" prefetch={false}>Se connecter</Link><Link className="button-secondary" href="/inscription" prefetch={false}>Créer un compte</Link></div></div>;
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.push("/"); router.refresh(); }
  async function removeAccount() { const response = await fetch("/api/account", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password, confirmation: "SUPPRIMER" }) }); const data = await response.json() as { error?: string }; if (!response.ok) { setError(data.error ?? "Suppression impossible."); return; } router.push("/"); router.refresh(); }
  async function cancelSubscription(payment: Payment) { if (!payment.subscriptionId) return; setCancelling(payment.id); setError(""); const response = await fetch("/api/paypal/cancel-subscription", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subscriptionId: payment.subscriptionId }) }); const data = await response.json() as { error?: string }; if (!response.ok) setError(data.error ?? "Annulation impossible."); else setPayments((current) => current.map((item) => item.id === payment.id ? { ...item, status: "CANCELLED" } : item)); setCancelling(null); }
  return <div className="grid gap-6">
    <section className="flex flex-col gap-5 rounded-[1.75rem] bg-navy p-6 text-white sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><p className="text-sm font-bold text-mint">Votre espace personnel</p><h1 className="mt-1 text-3xl font-black">Bonjour</h1><p className="mt-2 text-sm text-white/70">{user.email}</p></div><button className="button-light" onClick={logout}><LogOut className="h-4 w-4" />Déconnexion</button></section>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]">
      <section className="grid gap-6"><div className="rounded-[1.5rem] border border-border bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-primary">Suivi</p><h2 className="mt-1 text-2xl font-black text-ink">Mes démarches</h2></div><Link className="button-primary compact" href="/demarches/demenagement" prefetch={false}><Plus className="h-4 w-4" />Nouvelle</Link></div>{procedures.length ? <div className="mt-6 grid gap-3">{procedures.map((item) => <article className="flex items-center gap-4 rounded-2xl border border-border p-4" key={item.id}><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-secondary text-primary"><FileText className="h-5 w-5" /></span><div className="flex-1"><h3 className="font-black text-ink">{item.title}</h3><p className="text-xs text-muted-foreground">Mis à jour le {new Intl.DateTimeFormat("fr-FR").format(new Date(item.updatedAt))}</p></div></article>)}</div> : <div className="mt-6 rounded-2xl bg-muted/70 p-8 text-center"><CalendarDays className="mx-auto h-9 w-9 text-primary" /><p className="mt-3 font-bold text-ink">Aucune démarche sauvegardée</p><p className="mt-1 text-sm text-muted-foreground">Créez une checklist puis sauvegardez-la ici.</p></div>}</div>
      <div className="rounded-[1.5rem] border border-border bg-white p-6"><h2 className="text-xl font-black text-ink">Paiements et abonnements</h2>{payments.length ? <div className="mt-4 grid gap-3">{payments.map((payment) => <article className="flex flex-col gap-3 rounded-2xl border border-border p-4 sm:flex-row sm:items-center" key={payment.id}><div className="flex-1"><p className="font-bold text-ink">{payment.kind === "subscription" ? "Abonnement Premium" : "Dossier complet"}</p><p className="text-xs text-muted-foreground">{new Intl.NumberFormat("fr-FR", { style: "currency", currency: payment.currency }).format(payment.amountCents / 100)} · {payment.status}</p></div>{payment.subscriptionId && !["CANCELLED", "FAILED"].includes(payment.status) && <button className="button-secondary compact" disabled={cancelling === payment.id} onClick={() => cancelSubscription(payment)}>{cancelling === payment.id ? "Annulation…" : "Annuler l’abonnement"}</button>}</article>)}</div> : <p className="mt-3 text-sm text-muted-foreground">Aucun paiement enregistré.</p>}{error && <p className="mt-3 text-sm font-semibold text-destructive">{error}</p>}</div></section>
      <aside className="grid gap-4"><section className="rounded-[1.5rem] border border-border bg-white p-6"><h2 className="text-xl font-black text-ink">Mes données</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Téléchargez les données associées à votre compte au format JSON.</p><a className="button-secondary mt-4 w-full justify-center" href="/api/account" download><Download className="h-4 w-4" />Exporter</a></section><section className="rounded-[1.5rem] border border-red-200 bg-red-50 p-6"><h2 className="text-xl font-black text-red-900">Supprimer le compte</h2><p className="mt-2 text-sm leading-6 text-red-800">Cette action supprime les démarches et conversations associées. L’historique comptable est dissocié lorsque sa conservation est nécessaire.</p><AlertDialog><AlertDialogTrigger asChild><button className="mt-4 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-red-700 px-4 font-bold text-white"><Trash2 className="h-4 w-4" />Supprimer</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Supprimer définitivement votre compte ?</AlertDialogTitle><AlertDialogDescription>Cette action est irréversible. Confirmez avec votre mot de passe.</AlertDialogDescription></AlertDialogHeader><label><span className="form-label">Mot de passe</span><input className="form-input" type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <p className="text-sm font-semibold text-destructive">{error}</p>}<AlertDialogFooter><AlertDialogCancel>Annuler</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={removeAccount}>Supprimer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section></aside>
    </div>
  </div>;
}
