import { z } from "zod";
import { clearSessionCookie, getDatabase, requireUser, verifyPassword } from "@/lib/auth";
import { verifyMutationOrigin } from "@/lib/security";

export async function GET(request: Request) {
  try { const user = await requireUser(request); const db = getDatabase(); const [procedures, payments, conversations] = await Promise.all([db.prepare("SELECT id, type, title, data_json AS data, created_at AS createdAt, updated_at AS updatedAt FROM procedures WHERE user_id = ?").bind(user.id).all(), db.prepare("SELECT id, kind, status, amount_cents AS amountCents, currency, created_at AS createdAt FROM payments WHERE user_id = ?").bind(user.id).all(), db.prepare("SELECT id, created_at AS createdAt, expires_at AS expiresAt FROM conversations WHERE user_id = ? AND deleted_at IS NULL").bind(user.id).all()]); return Response.json({ exportedAt: new Date().toISOString(), account: { id: user.id, email: user.email, emailVerifiedAt: user.emailVerifiedAt }, procedures: procedures.results, payments: payments.results, conversations: conversations.results }, { headers: { "Content-Disposition": "attachment; filename=mes-donnees-demarches-claires.json" } }); } catch (error) { return Response.json({ error: error instanceof Error && error.message === "UNAUTHENTICATED" ? "Connexion requise." : "Export indisponible." }, { status: 401 }); }
}

export async function DELETE(request: Request) {
  if (!verifyMutationOrigin(request)) return Response.json({ error: "Requête refusée." }, { status: 403 }); const parsed = z.object({ password: z.string().min(1).max(128), confirmation: z.literal("SUPPRIMER") }).safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: "Confirmation invalide." }, { status: 400 });
  try { const user = await requireUser(request); const db = getDatabase(); const credentials = await db.prepare("SELECT password_hash AS hash, password_salt AS salt FROM users WHERE id = ?").bind(user.id).first<{ hash: string; salt: string }>(); if (!credentials || !(await verifyPassword(parsed.data.password, credentials.salt, credentials.hash))) return Response.json({ error: "Mot de passe incorrect." }, { status: 401 }); const now = new Date().toISOString(); await db.batch([db.prepare("DELETE FROM sessions WHERE user_id = ?").bind(user.id), db.prepare("DELETE FROM procedures WHERE user_id = ?").bind(user.id), db.prepare("DELETE FROM conversations WHERE user_id = ?").bind(user.id), db.prepare("UPDATE payments SET user_id = NULL WHERE user_id = ?").bind(user.id), db.prepare("UPDATE users SET email = ?, password_hash = 'deleted', password_salt = 'deleted', deleted_at = ?, updated_at = ? WHERE id = ?").bind(`deleted-${user.id}@invalid.local`, now, now, user.id)]); const headers = new Headers({ "Content-Type": "application/json" }); headers.append("Set-Cookie", clearSessionCookie(request.url)); return new Response(JSON.stringify({ ok: true }), { headers }); } catch { return Response.json({ error: "Suppression indisponible." }, { status: 503 }); }
}
